# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarTracker
pod 'SwiftIconFont'
pod 'CocoaMQTT'
pod "RxSwift"
pod "RxCocoa"
pod 'RealmSwift'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'NVActivityIndicatorView'
pod "SwiftSpinner"
#pod 'SwiftSVG', '~> 2.0'
#pod "Macaw"
pod 'Localize-Swift', '~> 3.2'
end
